org: joaquingp
app: aws-node-project
service: aws-node-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  app-api:
    handler: handler.handler
    environment:
      MONGO_URI: mongodb+srv://Admin:cdw0ALC3iqdD71xF@cluster0.8sisqpi.mongodb.net/nexo-test?retryWrites=true&w=majority
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"
